### ISSUE TITLE
npm run dev出错

### ISSUE THREAD

**Issue by jfhufhf** [xiaolu289/vue-think#1]
命令如下，系统为OS X
JordandeMacBook-Pro:frontend jordanvincent$ npm run dev

> fontend@1.0.0 dev /Applications/MAMP/htdocs/vuethink_v2/frontEnd
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:182                       i       throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fontend@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fontend@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jordanvincent/.npm/_logs/2018-03-10T02_46_38_045Z-debug.log

完整的日志：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.7.1
3 info using node@v8.1.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle fontend@1.0.0~predev: fontend@1.0.0
6 info lifecycle fontend@1.0.0~dev: fontend@1.0.0
7 verbose lifecycle fontend@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle fontend@1.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Applications/MAMP/htdocs/vuethink_v2/frontEnd/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet
9 verbose lifecycle fontend@1.0.0~dev: CWD: /Applications/MAMP/htdocs/vuethink_v2/frontEnd
10 silly lifecycle fontend@1.0.0~dev: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle fontend@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle fontend@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: fontend@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid fontend@1.0.0
15 verbose cwd /Applications/MAMP/htdocs/vuethink_v2/frontEnd
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.1.2
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error fontend@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the fontend@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
希望能解决下 谢谢！

**Comment by jfhufhf** [comment]
把frontend/config/index.js 中的host 地址改为127.0.0.1 解决这个问题。
